# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-03-09 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('headline', models.CharField(default='', max_length=50)),
                ('author', models.CharField(default='', max_length=50)),
                ('blog_text', models.TextField()),
            ],
        ),
    ]
