# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200413_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
